In [1]:
import numpy as np
import cv2

In [2]:
def bilinear_interpolation(img,out_dim):
    height,width,channels = img.shape
    scale_h,scale_w = height/out_dim[1],width/out_dim[0]
    emplyImage = np.zeros((out_dim[1],out_dim[0],channels),dtype=np.uint8)
    for i in range(out_dim[1]):
        for j in range(out_dim[0]):
            h,w = (i+0.5)*scale_h,(j+0.5)*scale_w
            h_org,w_org = h-0.5,w-0.5
            h_b0 = int(h_org)
            w_b0 = int(w_org)
            h_b1 = min(h_b0+1,height-1)
            w_b1 = min(w_b0+1,width-1)
            #h_0_gray = (h_b1-h_org)*img[h_b0,w_b0,:]+(h_org-h_b0)*img[h_b1,w_b0,:]
            #h_1_gray = (h_b1-h_org)*img[h_b0,w_b1,:]+(h_org-h_b0)*img[h_b1,w_b1,:]
            #emplyImage[i,j,:] = ((w_b1-w_org)*h_0_gray+(w_org-w_b0)*h_1_gray).astype(int)
            h_0_gray = (h_org-h_b0)*(img[h_b1,w_b0,:].astype(int)-img[h_b0,w_b0,:].astype(int))+img[h_b0,w_b0,:]
            h_1_gray = (h_org-h_b0)*(img[h_b1,w_b1,:].astype(int)-img[h_b0,w_b1,:].astype(int))+img[h_b0,w_b1,:]
            emplyImage[i,j,:] = ((w_org-w_b0)*(h_1_gray-h_0_gray)+h_0_gray).astype(int)
    return emplyImage

In [3]:
img = cv2.imread('lenna.png')
img_new1 = bilinear_interpolation(img,(800,800))
cv2.imshow('bilinear interp',img_new1)
cv2.waitKey()


-1

[[125 125 125 ... 111  99   0]
 [125 125 125 ... 111  99   0]
 [125 125 125 ... 111  99   0]
 ...
 [ 57  57  57 ...  80  80   0]
 [ 56  57  57 ...  80  81   0]
 [  0   0   0 ...   0   0   0]]
[[137 137 137 ... 131 113   0]
 [137 137 137 ... 131 113   0]
 [137 137 137 ... 131 113   0]
 ...
 [ 21  21  22 ...  70  71   0]
 [ 21  22  23 ...  70  72   0]
 [  0   0   0 ...   0   0   0]]
[[226 226 225 ... 221 209   0]
 [226 226 225 ... 221 209   0]
 [226 226 225 ... 221 209   0]
 ...
 [ 82  82  83 ... 179 182   0]
 [ 81  82  83 ... 180 183   0]
 [  0   0   0 ...   0   0   0]]
(800, 800)


[[125 125 133 ... 122 110  90]
 [125 125 133 ... 122 110  90]
 [125 125 133 ... 122 110  90]
 ...
 [ 60  60  58 ...  84  76  79]
 [ 57  57  62 ...  79  81  81]
 [ 57  57  62 ...  79  81  81]]


[[  0   0   0 ...   0   0  90]
 [  0   0   0 ...   0   0  90]
 [  0   0   0 ...   0   0  90]
 ...
 [230 230 208 ...  23   0  80]
 [  1   0   0 ...   0   0  81]
 [ 57  57  57 ...  80  81  81]]


[[ 0  0  0 ...  0  0 99]
 [ 0  0  0 ...  0  0 99]
 [ 0  0  0 ...  0  0 99]
 ...
 [ 0  0  0 ... 23  0 72]
 [ 1  0  0 ...  0  0 74]
 [22 22 23 ... 70 72 74]]
